Update to use ArcGIS runtime u10
Esri/maps-app-android pull request #188
Opened 2020-11-25 00:39 UTC by puneet-pdx

2021-02-19 23:52 UTC, sorenoid approved these changes
👍

2021-02-22 22:12 UTC, esreli requested changes
This PR looks good to me. Thanks for updating the project for U10 and certifying it still performs as expected.

Since the launch of the new dev-x site, I've noticed a number of broken links.

### README

- [license your app](https://github.com/Esri/maps-app-android/tree/puneet/updateToUseU10#licensing) leads to a `404`. Can we update the link to use the new dev-x site [link](https://developers.arcgis.com/android/license-and-deployment/)?

### docs/README

- [geocoding parameters](https://github.com/Esri/maps-app-android/tree/puneet/updateToUseU10/docs#geocoding) links to a `404`. 
- [The loadable pattern is described here.](https://github.com/Esri/maps-app-android/tree/puneet/updateToUseU10/docs#place-search) - links to `404`.
- [Portal API](https://github.com/Esri/maps-app-android/tree/puneet/updateToUseU10/docs#accessing-your-organizations-basemaps) - links to `404`.

Are there different links you can find to replace these?

2021-02-23 20:43 UTC, puneet-pdx commented
@esreli I have addressed your comments. Please have another look.

2021-02-23 21:52 UTC, esreli approved these changes
I think this is ready to go 👍

2021-02-23 21:52 UTC, esreli commented on README.md
> +For information about licensing your deployed app, see [License your app](https://developers.arcgis.com/android/license-and-deployment).
```suggestion
For information about licensing your deployed app, see [License your app](https://developers.arcgis.com/android/license-and-deployment/).
```

2021-02-23 21:52 UTC, esreli commented on build.gradle
> +    runnerVersion = '1.3.0'
What is this?

2021-02-23 21:52 UTC, esreli commented on docs/README.md
> +As an administrator of an ArcGIS Online organization or Portal, you can configure the basemaps that your users can switch between via a [group](http://doc.arcgis.com/en/arcgis-online/share-maps/share
```suggestion
As an administrator of an ArcGIS Online organization or Portal, you can configure the basemaps that your users can switch between via a [group](http://doc.arcgis.com/en/arcgis-online/share-maps/share-items.htm). Applications can leverage this configuration using the [Portal API](https://developers.arcgis.com/android/arcgis-organization-portals/). The Maps App does this by an asynchronous call to find the group containing web maps in the basemap gallery. With the returned group id, the collection of basemaps is retrieved from the portal.
```

2021-02-23 21:52 UTC, esreli commented on docs/README.md
> +You can also provision your own [custom geocode service](https://doc.arcgis.com/en/arcgis-online/administer/configure-services.htm#ESRI_SECTION1_0A9A071A7AB748028C8213D1D863FA18) to support your orga
```suggestion
You can also provision your own [custom geocode service](https://doc.arcgis.com/en/arcgis-online/administer/configure-services.htm#ESRI_SECTION1_0A9A071A7AB748028C8213D1D863FA18) to support your organization. Before using the `LocatorTask` to geocode or search for places, the `LocatorTask` must be `LOADED`. The loadable pattern is described [here](https://developers.arcgis.com/android/programming-patterns/loadable/). `LocatorTask` operations are performed asynchronously using `ListenableFutures`, an implementation of Java’s Future interface. `ListenableFutures` add the ability to attach a listener that runs upon completion of the task. One of the first user interactions the Maps App supports is suggesting places near the device location.
```

2021-02-24 20:08 UTC, puneet-pdx commented on build.gradle
> +    runnerVersion = '1.3.0'
version for android test runner

2021-02-24 21:38 UTC, merged